id: P000109
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །དཔལ་སྒྲུབ་པ་ཆེན་པོ་བཀའ་བརྒྱད་ཀྱི་སྤྱི་དོན་རྣམ་པར་བཤད་པ་དངོས་གྲུབ་སྙིང་པོ་ཞེས་བྱ་བ་བཞུགས་སོ།།
  authors:
  - མཛད་པ་པོ། འཇམ་མགོན་མི་ཕམ་རྒྱ་མཚོ།
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - yigchung
  id: SHE-RTD-026
web_metadata:
  title:
    en: The Essence of Accomplishment:A General Presentation of the Eight Herukas
      Practice
    bo: དཔལ་སྒྲུབ་པ་ཆེན་པོ་བཀའ་བརྒྱད་ཀྱི་སྤྱི་དོན་རྣམ་པར་བཤད་པ་དངོས་གྲུབ་སྙིང་པོ་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Treasury of Precious Termas–  Book 26
    bo: རིན་ཆེན་གཏེར་མཛོད།–  དེབ། ༢༦
  author:
    en: Jamgon Mipham Gyatso
    bo: འཇམ་མགོན་མི་ཕམ་རྒྱ་མཚོ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-RTD-026
  category:
    en: Deity Practice
    bo: བསྐྱེད་རིམ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-RTD-026.epub
  description:
    en: ''
    bo: ''
